version: "3.1"
services:
    webserver:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-webserver
        working_dir: /application
        networks:
            - internal
        volumes:
            - ./../:/application
            - ./sourcefiles/nginx:/etc/nginx/conf.d
        ports:
            - "${NGINX_PORT}:80"

    php-fpm:
        build: sourcefiles/php-fpm
        container_name: ${PROJECT_NAME}-php-fpm

        working_dir: /application
        environment:
            - PHP_WORKER_INSTALL_BCMATH=true
        volumes:
            - ./../:/application
            - ./sourcefiles/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        networks:
            - internal

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    mysql:
        image: mysql:8.1
        container_name: ${PROJECT_NAME}-mysql
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mysql-data:/var/lib/mysql'
            - './sourcefiles/mysql-init:/docker-entrypoint-initdb.d'
        ports:
            - '${DB_PORT}:3306'
        networks:
            - internal


    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}-phpmyadmin
        env_file:
            - .env
        ports:
            - '${DB_PORT_ADMIN}:80'
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        depends_on:
            - mysql
        networks:
            - internal

    redis:
        image: redis:latest
        container_name: ${PROJECT_NAME}-redis
        ports:
        - "6378:6379"

volumes:
    mysql-data:
        driver: local
networks:
    internal:
        driver: bridge
